# Generated by Django 5.1.7 on 2025-03-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "plate_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("group", models.CharField(max_length=10)),
            ],
        ),
    ]
