# Generated by Django 5.1.7 on 2025-03-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="group",
            new_name="type",
        ),
    ]
