# Generated by Django 5.1.7 on 2025-03-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_rename_group_vehicle_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="type",
            new_name="v_type",
        ),
    ]
